### ISSUE TITLE
 DO NOT see the character

### ISSUE THREAD

**Issue by Born2030** [ArtificialQualia/PyEveLiveDPS#37]
Hello, for some reason the program does not see the character. What can be wrong??

http://prntscr.com/k3h7g7

**Comment by ArtificialQualia** [comment]
Do you see a error message pop up like  
"Log file collision on characters:"  
or "Can't find the EVE logs directory."  
when you start PELD?

If not, can you attach the PELD log file?  You should find it here:  
C:\Users\\[username]\AppData\Roaming\PELD\PELD.log

**Comment by Born2030** [comment]
[PELD.log](https://github.com/ArtificialQualia/PyEveLiveDPS/files/2172188/PELD.log)

**Comment by Born2030** [comment]
no messages popped up

**Comment by ArtificialQualia** [comment]
Are you running EVE in a language other than english?  PELD currently has problems processing other languages since I don't speak them and this makes it difficult for me to write code for.

If possible, could you try changing your eve language to English and restart the client, then see if PELD detects the character?  If that works, then that is the issue.  I'll be looking at non-english language support with a later release.

**Comment by Born2030** [comment]
Hey. Yes, the transition to English has helped. I use Russian, and would be very grateful if Your program supported other languages.

**Comment by ArtificialQualia** [comment]
Sure, I'll prioritize adding in support for other EVE log languages.  It should be available in v2.1.0 unless there are any major issues.
