### ISSUE TITLE
Cap Xfer / Remote Reps not working.

### ISSUE THREAD

**Issue by RedViper9** [ArtificialQualia/PyEveLiveDPS#40]
Thanks for making a great app. The incoming/outgoing DPS tracking is fantastic and a much needed addition to Eve.

I tried using the other tracking features and was unable to see any other values. I was in a spider tanking fleet so we were doing remote armor repair, remote cap transfer, and of course DPS; however while DPS tracking continued functioning correctly, the other values all remained at zero and the graph corresponded by giving a flat line at zero. I double checked and the reps and cap transfer are present in my combat log files. Please let me know what I can provide to help with troubleshooting.

**Comment by ArtificialQualia** [comment]
Hi @RedViper9 

I'm not having any issues tracking those values, so I'll need a little bit more info from you if you don't mind.

Can you attach the PELD log file, found here:  
`C:\Users\[username]\AppData\Roaming\PELD\PELD.log`

That may not show anything though (but please attach it anyways!) since it is tracking other values with no issues.  It would be helpful if you could also attach the game log file that is giving you this issue, along with the approximate timestamp of the problem log entries and that should be all I need to fix it.

**Comment by ArtificialQualia** [comment]
Hey @RedViper9 are you still having this issue?

**Comment by ArtificialQualia** [comment]
Closing out the ticket until additional information can be provided.

**Comment by RedViper9** [comment]
Sorry for the delay in sending data. I'm still having this issue, attempted to send you the attachment as a response to one of the emails, but not sure it went through. The attached is a representative combat log with character and alliance names replaced.

[Combat Log with Logi.txt](https://github.com/ArtificialQualia/PyEveLiveDPS/files/2329981/Combat.Log.with.Logi.txt)

**Comment by ArtificialQualia** [comment]
Thanks for the log, I see the issue now.

It looks like you are using the Z-S overview pack (or something based off of that) which is adding newlines to entries in your log file and moves some things around that make it harder to parse.

I'll see what I can do about supporting these kinds of entries.  The actual values of the entries aren't hard to get in these cases, but the extra metadata like pilots, ship involved, etc. will be inconsistent at best as they could be formatted any way imaginable (or disabled completely), and are not 'regular'.

**Comment by ArtificialQualia** [comment]
This has been fixed in v2.2.0
