### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by ArchangelSin** [ArtificialQualia/PyEveLiveDPS#51]
Hi,

I've seen your DPS graph featured on a twitch stream. 
I was wondering if you could add a threshold line for active tank (Shield booster, armor repair or hull repair) so we could see if the incoming DPS goes over this threshold line. This way we can easily and clearly see if our active tank is enough.

Best regards,
ArchangelSin

**Comment by ArtificialQualia** [comment]
@ArchangelSin I wish I could add that!

Sadly, in order to comply with EVE's EULA, PELD can only track what information appears in the combat logs in EVE.  Local reps don't show up there, only remote reps do.  I've prodded CCP before to try to get that information added to the combat logs, but it doesn't look likely that it will happen.

Let me know if you have further questions/comments.
