### ISSUE TITLE
PELD api

### ISSUE THREAD

**Issue by lavacano** [ArtificialQualia/PyEveLiveDPS#64]
Hello, 

CCP is unable or unwilling to do logi through crest promised since 2018 wishlisted for much longer.  I would like an API into peld for logi to submit their healing/overhealing/cap efficacy to zlogiboard.com which will have battle report style killmails for logi.  PELD is a great parser and is trusted by the community.  I would love to collaborate on this while I do not have the technical experience necessary I do have resources and am willing to contribute to your project/collab to attain my goals.

**Comment by ArtificialQualia** [comment]
That sounds neat, but I'm not sure that will work here for a few reasons:

- Vast majority of players use PELD without the networking features (peld-fleet)
- I don't retain combat statistics on the server on purpose, this is a security benefit to the users
- The server would also have to get a whole lot bigger to support retaining and indexing a bunch of combat stats along with an api for accessing them
- Client-side programs can't be trusted.  Since this logi info wouldn't be coming from CCP's servers, there are only so many ways to verify what a client says has happened has actually happened.  This could lead to false data.
